### ISSUE TITLE
There must be "source" to activate the virtual environment in linux

### ISSUE THREAD

**Issue by rv-raman** [AbsurdNerd/SimplifyReport_Backend#2]
currently in the readme.md it is given as env\Scripts\activate. But in bash/linux terminal we need to enter "source" before it. So final command becomes "source env\Scripts\activate".

**Comment by diyajaiswal11** [comment]
You're right @venkataraman123 , Would you like to make the changes in the README file?

**Comment by venkataraman123** [comment]
Yes, mam.
